apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  labels:
    app: curriculum
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curriculum
  template:
    metadata:
      labels:
        app: curriculum
    spec:
      containers:
      - name: curriculum
        image: isaac21/curriculum:v1
        ports:
        - containerPort: 80
