apiVersion: apps/v1
kind: Service
metadata:
  name: web-service
  labels:
    app: curriculum
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 2001
    protocol: TCP
  selector:
    app: curriculum
